# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9077e8b75644886c301af181366948194b1ee0212a39d7d5f81a6bd14781b684f6c8e63e05e57f8ffb0d43d2ac1374ef679170eadcd4af78dc438e4b7a90eff

test:
  secret_key_base: 2f58042f7de820b65e93e87edf3f5d488785be3f28f22a07edc17d47cf09bfc7c6cbf410fb9eeca342523b0287419d3e7482fe1e7da97246f3b88b0142ce2f4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
